/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:098820e6-7e89-4e30-8ced-1229520cbed2",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_zWG230o3S",
    "aws_user_pools_web_client_id": "2k5750unj8ojlm9ubh6nglpsqa",
    "oauth": {
        "domain": "prime-app-authenticator-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://puox4ose3veu5eq27e5usdxlvu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    //"aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-zbjlo4m23nftljprcy7y3lxdpy"
};
export default awsmobile;